create database conn_ex;
use conn_ex;
select * from walmartsalesdata;
describe walmartsalesdata;

-- Q1. Calculate total number of transactions from data?
SELECT 
    COUNT(*) AS Total_Transactions
FROM
    walmartsalesdata;

-- Q2.What are Total_Revenue and Total_Income?
SELECT 
    ROUND(SUM(Total), 2) AS Total_Revenue,
    ROUND(SUM(gross_income), 2) AS Total_Income
FROM
    walmartsalesdata;

-- Q3.What was the total number of items sold?
SELECT 
    SUM(Quantity) AS Total_Quantity_sold
FROM
    walmartsalesdata;

-- Q4.How much Average Revenue generated per each transactions brings?
SELECT 
    ROUND(SUM(Total) / COUNT(*), 2) AS Avg_Revenue_per_Transaction
FROM
    walmartsalesdata;

-- Q5.What is the average rating given by customers across all transactions?
SELECT 
    ROUND(AVG(Rating),2) AS Avg_Customer_Rating
FROM
    walmartsalesdata;

-- Q6. Findout total sales by each brach and city?
SELECT 
    Branch, City, ROUND(SUM(Total),2) AS Total_Sales
FROM
    walmartsalesdata
GROUP BY Branch , City
ORDER BY Total_Sales DESC;

-- Q7.What was total sales and profit for each product_line 
SELECT 
    Product_line,
    ROUND(SUM(Total), 2) AS Total_sales,
    ROUND(SUM(gross_income), 2) AS Profit
FROM
    walmartsalesdata
GROUP BY Product_line
ORDER BY Total_sales DESC;



-- Q8.Find total sales coming through which payment methods?
SELECT 
    payment,
    ROUND(SUM(Total), 2) AS Total_sales,
    COUNT(*) AS Transactions
FROM
    walmartsalesdata
GROUP BY payment
ORDER BY Total_sales DESC;

-- Q9.What are the sales and profit trends for the months of January, February, and March?
SELECT 
    MONTHNAME(Date) AS Month_Name,
    ROUND(SUM(Total), 2) AS Monthly_Sales,
    ROUND(SUM(gross_income), 2) AS Monthly_Profit
FROM
    walmartsalesdata
GROUP BY Month_Name;

-- Q10 What is the total sales generated during weekends compared to weekdays?
SELECT 
    CASE 
        WHEN DAYOFWEEK(Date) IN (1, 7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS Day_Type,
    ROUND(SUM(Total), 2) AS Total_Sales
FROM walmartsalesdata
GROUP BY Day_Type;

-- Q11 During which hours of the day does the store record the highest sales?
SELECT 
    HOUR(Time) AS Hours,
    COUNT(*) AS Transacations,
    ROUND(SUM(Total), 2) AS Total_Sales
FROM
    walmartsalesdata
GROUP BY Hours
ORDER BY Total_Sales DESC;

-- Q12.What is the total gross income generated by each branch?
 SELECT 
    Branch, ROUND(SUM(gross_income), 2) AS Total_Gross_Income
FROM
    walmartsalesdata
GROUP BY Branch
ORDER BY Total_Gross_Income DESC;

-- Q13.What were the top 5 highest sales transactions in walmart sales?
SELECT 
    Invoice_ID, City, Branch, Product_line,Rating, Total AS Total_sales
FROM
    walmartsalesdata
ORDER BY Total_sales DESC
LIMIT 5;


-- Q14 What is the total sales and percentage contribution of each customer type to the overall sales?
SELECT 
    Customer_type,
    ROUND(SUM(Total), 2) AS Total_Sales,
    ROUND(SUM(Total) / (SELECT 
                    SUM(total)
                FROM
                    walmartsalesdata) * 100,
            2) AS Percentage
FROM
    walmartsalesdata
GROUP BY Customer_type;

-- Q15 What are the total sales and profit by gender, and which gender records the highest values?
SELECT 
    Gender,
    ROUND(SUM(Total), 2) AS Total_sales,
    ROUND(SUM(gross_income), 2) AS Total_Profit
FROM
    walmartsalesdata
GROUP BY Gender
ORDER BY Total_sales DESC;

----------------------------------------------------------------------------------------------------------

